parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     3306
    database_name:     nourriture
    database_user:     root
    database_password: Sh4nkl1n

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            6k?;rqpKhIi6&2x:&IP*,I.UxecEu$ YF/skS1+1*-sCa6SQ,R6[`#Fj-`8}u|I4')

#NOURRITURE GLOBAL CONFIGS
    #supported locales
    nourriture_locales: en|fr 
    
    #supported countries in forms etc
    nourriture_countries: [GB,FR,DE,PL] 
    
    nourriture_weights: [50,100,200,500] 

    #used for form locales	
    nourriture_preferred_locales: [en_GB,fr] 
