parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     3306
    database_name:     nourriture
    database_user:     root
    database_password: Sh4nkl1n

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            6k?;rqpKhIi6&2x:&IP*,I.UxecEu$ YF/skS1+1*-sCa6SQ,R6[`#Fj-`8}u|I4')
