sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /{_locale}/cart
    requirements:
       _locale: %nourriture_locales%
    #prefix: /cart

nourriture_front_endx:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
       _locale: %nourriture_locales%

system:
    resource: "@SystemBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}
    requirements:
       _locale: %nourriture_locales%
       
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    requirements:
       _locale: %nourriture_locales%

fos_user_register:
    #resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
       _locale: %nourriture_locales%

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
       _locale: %nourriture_locales%

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/password
    requirements:
       _locale: %nourriture_locales%
#user:
#    resource: "@UserBundle/Resources/config/routing.yml"
#    prefix:   /

#home:
#    resource: "@HomeBundle/Resources/config/routing.yml"
#    prefix:   /{_locale}
#    requirements:
#       _locale: %nourriture_locales%

nourriture_back_end:
    resource: "@BackEndBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
       _locale: %nourriture_locales%
nourriture_front_end:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
       _locale: %nourriture_locales%
