frontend_homepage:
    pattern:  /home
    defaults: { _controller: FrontEndBundle:FrontEnd:index }

frontend_products_list:
    pattern:  /products/list
    defaults: { _controller: FrontEndBundle:Products:list }

