parameters:
#    nourriture_front_end.example.class: Nourriture\FrontEndBundle\Example

services:
#    nourriture_front_end.example:
#        class: %nourriture_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
