<?php

namespace Nourriture\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostcodesAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostcodesAddressRepository extends EntityRepository{

   public function _findByPostcode($postcode){

        #die($postcode . __FILE__.__LINE__);

        $q = $this->createQueryBuilder('a')
                        ->select('a.postcode')
                        ->where('a.postcode LIKE :postcode')
                        ->setParameter('postcode', "%$postcode%")
                        ->orderBy('a.id','ASC');

			$q->expr()->concat('a.organisation','a.department');

                       $rs =  $q->getQuery()
                        ->getResult();
		var_dump($rs);
		die(__FILE__.__LINE__);

    }


}
