<?php

namespace Nourriture\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findByRole($role){

	/*return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM UserBundle:User u WHERE u.roles LIKE :role'
            )->setParameter("role", "%$role%")
		->getResult(); */
	return $this->createQueryBuilder('u')
			->select('u')
			->leftJoin('u.profile', 'p')
			->where('u.roles LIKE :role')
			->setParameter('role', "%$role%")
			->orderBy('u.username','ASC')
			->groupBy('u')
			->getQuery()
			->getResult();


    }

    public function findByFilter($array){

	if(count($array)==0) return null;

	#pagination
	#$q->setFirstResult(25);
	#$q->setMaxResults(25);		



        $q =  $this->createQueryBuilder('u')
                        ->select('u')
                        ->leftJoin('u.profile', 'p')
                        ->where('u.roles LIKE :role');

			$n = 1;

			foreach($array as $key=>$val){
				if($n==1){
				 $q->Where("u.$key LIKE '%$val%'");
				}else{
				  $q->orWhere("u.$key LIKE '%$val%'");
				}	

				$n++;

			}
                    
		     $q ->orderBy('u.username','ASC')
                        ->groupBy('u');

	return  $q->getQuery()->getResult();


    }

}
