nourriture_user_listener:
     class: Nourriture\UserBundle\EventListener\UserListener
     arguments: ["@router"]
     tags:
         - { name:kernel.event_listener, event: security.interactive_login, method: setLocale}
         - { name:kernel.event_listener, event: kernel.request, method: setLocaleForAuthenticatedUser}
