#nourriture_user_listener:
#     class: Nourriture\UserBundle\EventListener\UserListener
#     arguments: ["@router"]
#     tags:
#         - { name:kernel.event_listener, event: security.interactive_login, method: setLocale}
#         - { name:kernel.event_listener, event: kernel.request, method: setLocaleForAuthenticatedUser}
services:
     nourriture.profile.form.type:
        class: Nourriture\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nourriture_user_profile}
     nourriture.user_listener:
       class: Nourriture\UserBundle\EventListener\UserListener
       arguments: [@router, @security.context]
       tags:
           - { name: kernel.event_listener, event: security.interactive_login, method: setLocaleForAuthenticatedUser }
        #   - { name: kernel.event_listener, event: kernel.request, method: setLocaleForUnauthenticatedUser }
           - { name: kernel.event_listener, event: kernel.request, method: setLocaleForUser }

   #  nourriture.login_success_handler:
   #     class: Nourriture\UserBundle\EventListener\UserListener
   #     #arguments: [%fos_user.model.user.class%]
   #     tags:
   #         - { name: kernel.event_listener, event: security.interactive_login, method: onSuccess }

     nourriturea.user.registration.form.type:
        class: Nourriture\UserBundle\Form\Type\RegistrationFormType
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: nourriture_user_registration }

     nourriture.user.registration_handler:
        class: Nourriture\UserBundle\EventListener\UserRegistrationListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_subscriber, alias: nourriture_user_registration_listener }
